In [1]:
import torch

In [3]:
randint = torch.randint(-100,100,(6,))
print(randint)

tensor([ 64, -32, -10, -24, -88,  51])


In [ ]:
tensor = torch.tensor([[0.1,1.2], [2.2,3.1], [4.9, 5.2]])
print(tensor)

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])


In [6]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
randinput = torch.empty(2,3)
randinput

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
arange = torch.arange(9)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
linspace = torch.linspace(3,10, steps = 10)
linspace

tensor([ 3.0000,  3.7778,  4.5556,  5.3333,  6.1111,  6.8889,  7.6667,  8.4444,
         9.2222, 10.0000])

In [18]:
logspace = torch.logspace(start = -10,end= 10, steps= 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [19]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])