In [2]:
import torch

## torch method

In [3]:
# define a probablilty tensor
probabilities = torch.tensor([ 0.1, 0.9]) # is giving a tensor but read down for this 

# 10% or 0.1 => 0, 90% or 0.9 = 1. each probability points to the index of the probability in the tensor

# Draw 10 samples from the multinomial distribution
sample = torch.multinomial(probabilities,num_samples=10, replacement= True)
print(sample)



tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])


In [4]:
# tensor concat
tensorarray = torch.tensor([1,2,3,4,5])
out1 = torch.cat((tensorarray,torch.tensor([5,6])),dim= 0)
out1

tensor([1, 2, 3, 4, 5, 5, 6])

In [5]:
output2 = torch.tril(torch.ones(5,5)) # trill --> triangular lower
output2

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [6]:
output3 = torch.triu(torch.ones(5,5)) # trill --> triangular lower
output3

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [7]:
output3 = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf')) # trill --> triangular lower
output3

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [8]:
torch.exp(output3)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [9]:
inparr = torch.zeros(2,3,4)
transpose = inparr.transpose(0,2)
transpose.shape

torch.Size([4, 3, 2])

In [10]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### neural network (nn)

In [11]:
import torch.nn as nn

sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)   #3-> input neurons , 3 -> output neuron
print(linear(sample))

tensor([ 5.2199,  6.6448, -4.5046], grad_fn=<SqueezeBackward4>)


In [12]:
import torch.nn.functional as F

tensor = torch.tensor([1.0,2.0,3.0])

softmax_output = F.softmax(tensor,dim=0) ## take elements of tensor put it in exp^element ,
                                                 ##     then sum of all ,, then e^each element divide by the sum
softmax_output

tensor([0.0900, 0.2447, 0.6652])

### embedding vector 

In [16]:
# 1. Define embedding layer
vocab_size = 100      # number of unique words (tokens) in vocabulary
embedding_dim = 100   # size of each embedding vector
embedding = nn.Embedding(vocab_size, embedding_dim)

# 2. Input indices
input_index = torch.LongTensor([1, 5, 8, 3, 2])

# 3. Lookup embeddings
embedded_output = embedding.forward(input_index) ## embedding(input_index)

print(embedded_output.shape)
##print(embedded_output)



torch.Size([5, 100])


In [14]:
## matrix multiply 
matrix1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

matrix_mul = (matrix1 @ matrix2)
matrix_mul2 = torch.matmul(matrix1,matrix2)
print(matrix_mul.shape)
print(matrix_mul2.shape)


torch.Size([3, 3])
torch.Size([3, 3])


In [15]:
int_64 = torch.randint(1,(3,2))

folat_32 = torch.rand(2,3)

print(torch.matmul(int_64,folat_32))

RuntimeError: expected m1 and m2 to have the same dtype, but got: long long != float